# Generated by Django 4.2.9 on 2026-05-10 12:17

import hashlib
import hmac

from django.conf import settings
from django.db import migrations, models


def _derived_hmac_key():
    return hmac.new(
        settings.SECRET_KEY.encode("utf-8"),
        b"bookings.Ticket.security_code.v1",
        hashlib.sha256,
    ).digest()


def _build_security_code(qr_code_data: str) -> str:
    if not qr_code_data:
        return ""
    digest = hmac.new(
        _derived_hmac_key(),
        qr_code_data.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    hex16 = digest[:16].upper()
    return "-".join(hex16[i : i + 4] for i in range(0, 16, 4))


def forwards(apps, schema_editor):
    Ticket = apps.get_model("bookings", "Ticket")
    for t in Ticket.objects.select_related("booking").iterator():
        data = t.qr_code_data
        if not data:
            data = f"TICKET:{t.ticket_number}:{t.booking.event_id}"
            Ticket.objects.filter(pk=t.pk).update(qr_code_data=data)
        code = _build_security_code(data)
        Ticket.objects.filter(pk=t.pk).update(security_code=code)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="security_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Manual check-in code (HMAC of qr_code_data); same ticket as QR scan",
                max_length=19,
                null=True,
            ),
        ),
        migrations.RunPython(forwards, noop),
        migrations.AlterField(
            model_name="ticket",
            name="security_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Manual check-in code (HMAC of qr_code_data); same ticket as QR scan",
                max_length=19,
                unique=True,
            ),
        ),
    ]
