# Generated by Django 4.2.9 on 2026-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="match_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sports match data including team logos",
            ),
        ),
    ]
