release: DJANGO_SETTINGS_MODULE=ticketsystem.production_settings python manage.py migrate --noinput && python manage.py create_superuser_if_not_exists
web: DJANGO_SETTINGS_MODULE=ticketsystem.production_settings gunicorn ticketsystem.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
